version: 2

references:
  repository_root: &repository_root
    /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  load_code: &load_code
    run:
      name: load code from workspace
      command: |
        # Move all files and dotfiles to current directory
        shopt -s dotglob
        mv /tmp/workspace/app/* .
        shopt -u dotglob

jobs:

  checkout_code:
    working_directory: ~/app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - run:
          command: |
            mkdir -p /tmp/workspace/app
            shopt -s dotglob
            mv * /tmp/workspace/app/
            shopt -u dotglob
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - app

  build:
    working_directory: *repository_root
    docker:
      - image: vvakame/circleci-gaego:latest
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      DISPLAY: ":99"
    steps:
      - *attach_workspace
      - *load_code

      - restore_cache:
          keys:
            - dep-cache-{{ checksum "go/Gopkg.lock" }}
            - dep-cache-
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "node/my-app/package.json" }}
            - npm-cache-

      - run: ls -al /tmp/workspace/app/

      - run: ls -al
      - run: printenv
      - run: go version
      - run: goapp version
      - run: goapp env
      - run: npm version

      - run:
          name: build go
          working_directory: go
          command: |
            make setup

      - run: ls -al

      - run:
          name: test go
          working_directory: go
          command: |
            make test

      - run:
          name: build node
          working_directory: node/my-app
          command: |
            npm install
            npm run build

      - run:
          name: test node
          working_directory: node/my-app
          command: |
            npm run lint
            # npm test

      # cache
      - save_cache:
          key: dep-cache-{{ checksum "go/Gopkg.lock" }}
          paths:
            - go/vendor
      - save_cache:
          key: npm-cache-{{ checksum "node/my-app/package.json" }}
          paths:
            - node/my-app/node_modules

      # persist_to_workspace
      - run:
          name: persist to workspace
          command: |
            rm -rf /tmp/workspace/app/go
            cp -r go /tmp/workspace/app
            rm -rf /tmp/workspace/app/node
            cp -r node /tmp/workspace/app
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - app/go
            - app/node

  deploy:
    working_directory: *repository_root
    docker:
      - image: vvakame/circleci-gaego:latest
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      DISPLAY: ":99"
    steps:
      - *attach_workspace
      - *load_code
      - run: ls -al /tmp/workspace/app/

      - run: ls -al go node
      - run: printenv

      - run: ls -al go/app

      - run: cp -r node/my-app/dist go/app

      - run: ls -al go/app

      - deploy:
          name: Deploy
          command: |
            echo "deploy done!"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
