version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go mod download
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg/mod

workflows:
  build:
    jobs:
      - build
