version: 2

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  load_code: &load_code
    run:
      name: load code from workspace
      command: |
        # Move all files and dotfiles to current directory
        mv /tmp/workspace/app/* /tmp/workspace/app/.[!.]* .

jobs:

  checkout_code:
    working_directory: ~/app
    docker:
      - image: google/cloud-sdk:178.0.0
    steps:
      - checkout
      - run:
          command: |
            mkdir -p /tmp/workspace/app
            mv * .[!.]* /tmp/workspace/app/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - app

  build:
    working_directory: /go/src/github.com/shigwata/circleci-test
    docker:
      - image: circleci/golang:1.8
    environment:
      GAE_GO_SDK_VERSION: 1.9.61
    steps:
      - *attach_workspace
      - *load_code
      - run: ls
      - run: go version
      - run: printenv

      - run:
          name: Install go_appengine
          working_directory: ${HOME}GAE_GO_SDK_VERSION
          command: |
            curl -o go_appengine.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-${GAE_GO_SDK_VERSION}.zip
            unzip -q -d $HOME go_appengine.zip
            echo 'export PATH=$PATH:$HOME/go_appengine' >> $BASH_ENV
      - run: goapp version
      - run: goapp env

      - run: |
          mkdir -p ./go/
          touch ./go/go.txt
          ls ./go/
          mkdir -p /tmp/workspace/app/go/
          mv ./go/* /tmp/workspace/app/go/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - app/go

  build_java:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - *attach_workspace
      - *load_code
      - run: ls
      - run: java -version
      - run: mvn --version
      - run: printenv
      - run: |
          mkdir -p ./java/
          touch ./java/java.txt
          ls ./java/
          mkdir -p /tmp/workspace/app/java/
          mv ./java/* /tmp/workspace/app/java/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - app/java

  deploy:
    working_directory: ~/app
    docker:
      - image: google/cloud-sdk:178.0.0
    steps:
      - *attach_workspace
      - *load_code
      - run: ls
      - run: ls ./go
      - run: ls ./java
      - run: gcloud --version
      - run: printenv

      - run:
          name: Install go_appengine
          working_directory: ${HOME}GAE_GO_SDK_VERSION
          command: |
            curl -o go_appengine.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-${GAE_GO_SDK_VERSION}.zip
            unzip -q -d $HOME go_appengine.zip
            echo 'export PATH=$PATH:$HOME/go_appengine' >> $BASH_ENV
      - run: goapp version
      - run: goapp env

      - run: echo "deploy done!"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - build_java:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
            - build_java
